In [1]:
# 1. What is a Python library? Why do we use Python libraries?
#A Python library is a collection of pre-written code and functionalities that can be imported and used in Python programs. Libraries typically contain modules, functions, classes, and constants that serve specific purposes or solve particular problems.



In [ ]:
#2. What is the difference between Numpy array and List?
# NumPy arrays are more suitable for numerical computations, large datasets, and multidimensional data, while Python lists are more versatile and suitable for general-purpose programming and handling heterogeneous data.

In [8]:
# 3. Find the shape, size and dimension of the following array?
import numpy as np
arr1= np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

arr1.shape
arr1.size




12

In [9]:
# 4. 4. Write python code to access the first row of the following array?

arr1= np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr1[0]

array([1, 2, 3, 4])

In [11]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

arr1 = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr1[2][3]





12

In [ ]:
# 6. 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extracting odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


In [14]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.87437332 0.00767737 0.52349935]
 [0.62842957 0.09215263 0.32246425]
 [0.73500033 0.19857562 0.59614136]]


In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?
# np.random.rand generates random values from a uniform distribution over the interval [0, 1), while np.random.randn generates random values from a standard normal distribution with mean 0 and standard deviation 1.






In [19]:
# 9.  Write code to increase the dimension of the following array?

arr1 = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr2= np.expand_dims(arr1,axis=0)
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [22]:
# 10. How to transpose the following array in NumPy?

arr1= np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr2 = arr1.T
arr2

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [25]:
# 11. 11. Consider the following matrix:

# Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

# Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


#Perform the following operation using Python1
# 1.Index wise multiplication
# 2.Matrix multiplication
# 3.Add both the matrics
# 4.Subtract matrix B from A
# 5.Divide Matrix B by A

import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A * B

# 2. Matrix multiplication
matrix_multiplication = np.dot(A, B.T) # Using transpose of B for matrix multiplication

# 3. Add both matrices
addition = A + B

# 4. Subtract matrix B from A
subtraction = A - B

# 5. Divide Matrix B by A
division = B / A

# Print results
print("1. Index wise multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix multiplication:")
print(matrix_multiplication)

print("\n3. Addition of matrices:")
print(addition)

print("\n4. Subtraction of matrix B from A:")
print(subtraction)

print("\n5. Division of Matrix B by A:")
print(division)








1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition of matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction of matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Division of Matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

# In NumPy, you can use the byteswap() function to swap the byte order of an array. This function creates a new array with the byte order swapped without changing the original array.

In [ ]:
# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. In other words, it calculates the inverse of a given matrix.


In [ ]:
# 14. What does the np.reshape function do, and how is it used?

#The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to reorganize the elements of an array into a different shape while preserving the total number of elements.

# The general syntax of np.reshape is:
# np.reshape(a, newshape, order='C')

In [ ]:
# 15. What is broadcasting in Numpy?
# Broadcasting in NumPy refers to a set of rules that allow arrays with different shapes to be combined or operated on together. It allows for arithmetic operations to be performed on arrays of different shapes without the need for explicit expansion or copying of data.

#The broadcasting rules in NumPy are designed to allow operations to be performed efficiently, while also ensuring that the semantics of the operation are preserved.

#The main idea behind broadcasting is to extend smaller arrays so that they have compatible shapes with larger arrays, and then perform element-wise operations between them. The broadcasting rules define how this extension is done.